# Generated by Django 3.0.1 on 2020-05-26 14:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('feedback', 'FEEDBACK'), ('suggestion', 'SUGGESTION')], default='feedback', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1024)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('submit_date', models.DateTimeField(default=datetime.datetime(2020, 5, 26, 14, 34, 47, 242610, tzinfo=utc))),
            ],
        ),
    ]
