# Generated by Django 3.0.1 on 2020-05-26 15:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('suggestionbox', '0004_auto_20200526_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 15, 40, 26, 696012, tzinfo=utc)),
        ),
    ]
