# Generated by Django 3.0.1 on 2020-06-10 13:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('suggestionbox', '0006_auto_20200610_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 10, 13, 39, 22, 708410, tzinfo=utc)),
        ),
    ]
